### ISSUE TITLE
Problem with audio in Android. It stops after 6:20 minutes

### ISSUE THREAD

**Issue by csacchetti** [google/flutter.plugins#34] opened 2019-12-20 21:54 UTC
I found a problem. In my app, I load a lot of small audio files in sequence, one after another. With iOS there are no problems, and I can continue indefinitely, with Android I have the problem that is when he's in the backgrounds, even when it s not background, that the audio stopping at 6 minutes and 20 seconds. At this point, the audio cannot be restored and I have to close and reopen the app. I don't think it s a code problem because in iOS I don't have any problems. Maybe it's a memory management problem. As I said before, it happens in the same spot with background music and not.

**Comment by monkeyswarm** [comment] 2019-12-20 22:36
Duplicate of #31

**Closed as completed by monkeyswarm** 2019-12-20 22:36 UTC
